version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/

hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 1000
      runas: root
      # env:
      #   PORT: 8080
      #   GIN_MODE: release
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: root